### ISSUE TITLE
App development experience

### ISSUE THREAD

**Issue by jarulraj** [DevThinkAI/ChatWithFiles#1]
Hey @samkeen. This is not really an issue -- more like a discussion. I noticed that you have built multiple AI apps recently for chatting with files and videos recently. We are building EvaDB to enhance and simplify this development experience. It would be *very helpful* if you could take a few minutes to check out EvaDB and share your thoughts:

1. PDF QA: https://github.com/georgia-tech-db/eva/tree/master/apps/privategpt
2. Youtube QA: https://github.com/georgia-tech-db/eva/tree/master/apps/youtube_qa

Thanks so much for consideration.

**Comment by samkeen** [comment]
Hey Joy, thanks for sharing, I'll take a look, but in all honesty, to a large extent I'm really just hacking a round at this point.
SQL syntax is an interesting idea, I'll add it to an upcoming [newsletter](https://devthinkai.beehiiv.com/) as tech to watch

**Comment by jarulraj** [comment]
Got it, thanks @samkeen.
